# act -W .github/workflows/build.yaml workflow_dispatch
name: Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: adservice
          - name: cartservice
            context: src
          - name: checkoutservice
          - name: currencyservice
          - name: emailservice
          - name: frontend
          - name: paymentservice
          - name: productcatalogservice
          - name: recommendationservice
          - name: shippingservice
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: src/${{ matrix.service.name }}/${{ matrix.service.context || '' }}
          tags: |
            ghcr.io/henrywhitakercommify/microservices-demo/${{ matrix.service.name }}:latest
            ghcr.io/henrywhitakercommify/microservices-demo/${{ matrix.service.name }}:${{ github.ref_name }}
