# act -W .github/workflows/build.yaml workflow_dispatch
name: Build and Publish with Skaffold

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Skaffold
      uses: heypigeonhq/setup-skaffold@3b1a0687de1b580d3879bf6b9d423255c9954587 #v1.1.0
      with:
        version: '2.16.1'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Skaffold build local
      # only build if tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        SKAFFOLD_DEFAULT_REPO=ghcr.io/henrywhitakercommify \
        skaffold build \
          --push=true \
          --filename='skaffold.yaml' \
          --build-concurrency=0